language: python

dist: bionic

services:
  - docker

addons:
  apt:
    packages:
      - python3-dev
      - libssl-dev
      - libffi-dev

python: 3.7

cache: pip

install:
  - pip3 install -r requirements/tests.txt

env:
  - APP_CONFIG="config.TestingConfig" SECRET_KEY="super secret key" PATH=$PATH:${HOME}/google-cloud-sdk/bin

before_script:
  - ./scripts/test_db.sh
  - export DATABASE_URL=postgresql://test@localhost:5433/test
  - export TEST_DATABASE_URL=postgresql://test@localhost:5433/test
  - bash scripts/test_multiple_heads.sh

script:
  - pytest tests -v --cov=.

after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
  - bash scripts/push_api_docs.sh

branches:
  only:
    - master
    - development
